# version: 2
#
# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.10"
#   apt_packages:
#     - default-jdk-doc
#     - default-jdk
#   commands:
#     - javadoc -d _readthedocs/html modules/java_api/org/intel/openvino/*.java


version: 2

build:
  image: latest
  apt_packages:
    - default-jdk-doc
