trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - modules/nvidia_plugin
    - modules/openvino_code

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - modules/nvidia_plugin
    - modules/openvino_code

resources:
  repositories:
  - repository: openvino
    type: github
    endpoint: openvinotoolkit
    name: openvinotoolkit/openvino
    ref: releases/2024/1

  - repository: testdata
    type: github
    endpoint: openvinotoolkit
    name: openvinotoolkit/testdata
    ref: releases/2024/1

jobs:
- job: Win
  timeoutInMinutes: 90

  pool:
    name: WIN_VMSS_VENV_F8S_WU2

  variables:
    system.debug: true
    VSTS_HTTP_RETRY: 5
    VSTS_HTTP_TIMEOUT: 200
    BUILD_TYPE: Release
    REPO_DIR: $(Build.Repository.LocalPath)
    OPENVINO_REPO_DIR: $(REPO_DIR)\..\openvino
    MODELS_PATH: $(REPO_DIR)\..\testdata
    WORK_DIR: $(Pipeline.Workspace)\_w
    BUILD_DIR: D:\build
    BUILD_DIR_CONTRIB: D:\build_contrib
    BUILD_WHEEL_DIR: D:\wheels
    MSVS_VARS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    MSVC_COMPILER_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\cl.exe
    INSTALL_DIR: $(WORK_DIR)\install_pkg
    SETUPVARS: $(INSTALL_DIR)\setupvars.bat
    GRADLE_VER: 7.1.1
    PYTHON_EXE: C:\hostedtoolcache\windows\Python\3.8.2\x64\python.exe

  steps:
  - script: |
      powershell -command "Invoke-RestMethod -Headers @{\"Metadata\"=\"true\"} -Method GET -Uri http://169.254.169.254/metadata/instance/compute?api-version=2019-06-01 | format-custom"
      where $(PYTHON_EXE)
      $(PYTHON_EXE) --version
      where java
      java -version
      wmic computersystem get TotalPhysicalMemory
      wmic cpu list
      wmic logicaldisk get description,name
      wmic VOLUME list
      set
    displayName: 'System info'

  - script: |
      rd /Q /S $(WORK_DIR) & mkdir $(WORK_DIR)
      rd /Q /S $(BUILD_DIR) & mkdir $(BUILD_DIR)
      rd /Q /S $(BUILD_DIR_CONTRIB) & mkdir $(BUILD_DIR_CONTRIB)
    displayName: 'Make dir'

  - checkout: self
    clean: true
    lfs: false
    submodules: recursive
    path: openvino_contrib

  - checkout: openvino
    clean: true
    lfs: false
    submodules: recursive
    path: openvino

  - checkout: testdata
    clean: true
    lfs: true
    path: testdata

  - script: |
      rem Speed up build
      powershell -command "Invoke-WebRequest https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip -OutFile ninja-win.zip"
      powershell -command "Expand-Archive -Force ninja-win.zip"
      powershell -command "Invoke-WebRequest https://services.gradle.org/distributions/gradle-$(GRADLE_VER)-bin.zip -OutFile gradle-$(GRADLE_VER)-bin.zip"
      powershell -command "Expand-Archive -Force gradle-$(GRADLE_VER)-bin.zip"
      call $(SETUPVARS) -pyver 3.8
      $(PYTHON_EXE) -m pip install --upgrade pip
      $(PYTHON_EXE) -m pip install -r $(OPENVINO_REPO_DIR)\src\bindings\python\wheel\requirements-dev.txt
      powershell -command "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      choco install opencv -y
    workingDirectory: $(WORK_DIR)
    displayName: 'Install dependencies'

  - script: |
      set PATH=$(WORK_DIR)\ninja-win;%PATH%
      call "$(MSVS_VARS_PATH)"
      cmake -GNinja ^
        -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) ^
        -DBUILD_nvidia_plugin=OFF ^
        -DENABLE_OV_TF_FRONTEND=OFF ^
        -DENABLE_OV_PADDLE_FRONTEND=OFF ^
        -DENABLE_OV_TF_LITE_FRONTEND=OFF ^
        -DENABLE_OV_PYTORCH_FRONTEND=OFF ^
        -DENABLE_INTEL_GPU=OFF ^
        -DENABLE_CPPLINT=OFF ^
        -DENABLE_SAMPLES=OFF ^
        -DENABLE_PYTHON=ON ^
        -DENABLE_JS=OFF ^
        -DCMAKE_C_COMPILER:PATH="$(MSVC_COMPILER_PATH)" ^
        -DCMAKE_CXX_COMPILER:PATH="$(MSVC_COMPILER_PATH)" ^
        $(OPENVINO_REPO_DIR)
    workingDirectory: $(BUILD_DIR)
    displayName: 'CMake OpenVINO'

  - script: dir $(OPENVINO_REPO_DIR)\temp\ /s
    displayName: 'List temp SDKs'

  - script: call "$(MSVS_VARS_PATH)" && $(WORK_DIR)\ninja-win\ninja
    workingDirectory: $(BUILD_DIR)
    displayName: 'Build OpenVINO'

  - script: dir $(OPENVINO_REPO_DIR)\bin\ /s
    displayName: 'List bin files'

  - script: cmake -DCMAKE_INSTALL_PREFIX=$(INSTALL_DIR) -P cmake_install.cmake
    workingDirectory: $(BUILD_DIR)
    displayName: 'Install OpenVINO'

  - script: dir $(INSTALL_DIR) /s
    displayName: 'List install files'

  - script: |
      set PATH=$(WORK_DIR)\ninja-win;%PATH%
      set OpenCV_DIR=C:\tools\opencv\build
      call $(SETUPVARS) -pyver 3.8
      call "$(MSVS_VARS_PATH)"
      cmake -GNinja ^
        -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) ^
        -DCMAKE_C_COMPILER:PATH="$(MSVC_COMPILER_PATH)" ^
        -DCMAKE_CXX_COMPILER:PATH="$(MSVC_COMPILER_PATH)" ^
        $(REPO_DIR)\modules\custom_operations
    workingDirectory: $(BUILD_DIR_CONTRIB)
    displayName: 'CMake OpenVINO Contrib'

  - script: call "$(MSVS_VARS_PATH)" && $(WORK_DIR)\ninja-win\ninja
    workingDirectory: $(BUILD_DIR_CONTRIB)
    displayName: 'Build OpenVINO Contrib'

  - script: |
      call $(SETUPVARS)
      set PATH=$(WORK_DIR)\gradle-$(GRADLE_VER)-bin\gradle-$(GRADLE_VER)\bin;%PATH%
      gradle clean build --info
      gradle test -Prun_tests -DMODELS_PATH=$(MODELS_PATH) -Ddevice=CPU --info
    workingDirectory: $(REPO_DIR)\modules\java_api
    displayName: 'Java tests'

  - script: |
      call C:\tools\opencv\build\setup_vars_opencv4.cmd
      call $(SETUPVARS) -pyver 3.8 && ^
      $(PYTHON_EXE) -m pip install -r $(REPO_DIR)\modules\custom_operations\tests\requirements.txt
      $(PYTHON_EXE) -m pytest -k "not sparse_conv" tests\run_tests.py
    env:
        CUSTOM_OP_LIB: $(BUILD_DIR_CONTRIB)\user_ie_extensions\user_ov_extensions.dll
    workingDirectory: $(REPO_DIR)\modules\custom_operations
    displayName: 'Custom user operation tests'
