name: Code Style
on:
  push:
    paths:
      - '**'
      - '!modules/nvidia_plugin/**'
  pull_request:
    paths:
      - '**'
      - '!modules/nvidia_plugin/**'

jobs:
  Java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install dependencies
        run: |
          wget -nc https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar

      - name: Check code style
        run: |
          java -jar google-java-format-1.9-all-deps.jar --set-exit-if-changed -a -i $(find . -type f -name "*.java")

      - name: Create code style diff
        if: failure()
        run: |
          git diff >java_code_style_diff.patch

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: java_code_style_diff
          path: java_code_style_diff.patch
