name: Code Style
on:
  push:
    paths:
      - 'modules/java_api/**'
  pull_request:
    paths:
      - '.github/workflows/code_style.yml'
      - 'modules/java_api/**'

jobs:
  Java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Install dependencies
        run: |
          wget -nc https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar

      - name: Check code style
        run: |
          java -jar google-java-format-1.9-all-deps.jar --set-exit-if-changed -a -i $(find . -type f -name "*.java")

      - name: Create code style diff
        if: failure()
        run: |
          git diff >java_code_style_diff.patch

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: java_code_style_diff
          path: java_code_style_diff.patch
