name: cuda history
on: push
jobs:
  history:
    runs-on: lohika-ci
    steps:
    - name: fetch
      run: git -C ~/runner/openvino_contrib fetch
    - name: rebased
      run: git -C ~/runner/openvino_contrib merge-base --is-ancestor origin/releases/2021/4 $GITHUB_SHA
    - name: autosquashed
      run: "! git -C ~/runner/openvino_contrib rev-list --pretty=oneline  -E --grep '^(fixup|squash|amend)!' origin/releases/2021/4..$GITHUB_SHA | fgrep !"
