name: cuda history
on: [push, pull_request]
jobs:
  history:
    runs-on: lohika-ci
    steps:
    - name: delete temporary branch
      run: git -C ~/runner/openvino_contrib branch -D temporary-ci-branch | echo 1
    - name: fetch
      run: git -C ~/runner/openvino_contrib fetch origin $GITHUB_REF:temporary-ci-branch
    - name: rebased
      run: git -C ~/runner/openvino_contrib merge-base --is-ancestor origin/releases/2021/4 $GITHUB_SHA
    - name: autosquashed
      run: "! git -C ~/runner/openvino_contrib rev-list --pretty=oneline  -E --grep '^(fixup|squash|amend)!' origin/releases/2021/4..$GITHUB_SHA | fgrep !"
