name: History CUDA
on:
  push:
    paths:
      - 'modules/nvidia_plugin/**'
  pull_request:
    paths:
      - 'modules/nvidia_plugin/**'
      - '.github/workflows/history_cuda.yml'
jobs:
  history:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout master branch
      uses: actions/checkout@v3
      with:
        ref: releases/2023/3
        fetch-depth: 0
    - name: delete temporary branch
      run: git branch -D temporary-ci-branch | echo 1
    - name: fetch
      run: git fetch origin $GITHUB_REF:temporary-ci-branch
    - name: rebased
      run: git merge-base --is-ancestor origin/releases/2023/3 temporary-ci-branch
    - name: autosquashed
      run: "! git rev-list --pretty=oneline  -E --grep '^(fixup|squash|amend)!' origin/releases/2023/3..temporary-ci-branch | fgrep !"
