name: precommit

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  paths:
    - 'modules/llama_cpp_plugin/**'

jobs:
  build_ubuntu20:
    runs-on: ubuntu-20.04
    steps:
     - name: Setup cmake
       uses: jwlawson/actions-setup-cmake@v1.14
       with:
         cmake-version: '3.24.x'

      - name: Checkout openvino_contrib
        uses: actions/checkout@v3
        submodules: recursive

      - name: Checkout openvino
        uses: actions/checkout@v3
        submodules: recursive
        repository: https://github.com/vshampor/openvino

      - name: CMake - configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DOPENVINO_EXTRA_MODULES=${{ github.workspace }}/openvino_contrib/modules -DBUILD_java_api=OFF -DBUILD_nvidia_plugin=OFF -DBUILD_custom_operations=OFF -DBUILD_openvino_code=OFF -DBUILD_token_merging=OFF -DENABLE_TESTS=ON -DENABLE_FUNCTIONAL_TESTS=ON -DENABLE_PLUGINS_XML=ON .

      - name: CMake - build
        run: cmake --build build -j`nproc` -- llama_cpp_plugin llama_cpp_e2e_tests

      - name: Upload build artifacts
        uses: alehechka/upload-tartifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}/bin/intel64/Release/

  test_ubuntu20:
    needs: build_ubuntu20
    runs-on: ubuntu-20.04
    steps:
      - name: Download build artifacts
        uses: alehechka/download-tartifact@v2
        with:
          name: build_artifacts
          path: binaries

      - name: Run E2E tests
        run:  ${{ github.workspace }}/binaries/llama_cpp_e2e_tests
