name: PyTorch Conversion
on: [push, pull_request]

jobs:
  convert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Clone OpenVINO
        run: |
          git clone --depth 1 https://github.com/openvinotoolkit/openvino/

      - name: Build OpenVINO
        run: |
          cd openvino
          git submodule update --init --recursive
          mkdir build && cd build
          python3 -m pip install cython
          cmake \
            -DENABLE_CLDNN=OFF \
            -DENABLE_VPU=OFF \
            -DENABLE_TESTS=OFF \
            -DENABLE_OPENCV=OFF \
            -DENABLE_SAMPLES=OFF \
            -DENABLE_PYTHON=ON \
            -DPYTHON_EXECUTABLE=`which python3` \
            -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
            -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..
          make -j$(nproc)

      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/openvinotoolkit/testdata
          python3 -m pip install \
                 numpy \
                 defusedxml \
                 networkx \
                 test-generator==0.1.1 \
                 torch \
                 torchvision

          git clone --depth 1 https://github.com/facebookresearch/detectron2
          python3 -m pip install -e detectron2

      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=./openvino/bin/intel64/Release/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=./openvino/bin/intel64/Release/lib/python_api/python3.6:$PYTHONPATH
          export PYTHONPATH=./openvino/model-optimizer:$PYTHONPATH
          export PYTHONPATH=./modules/mo_pytorch:$PYTHONPATH
          export MODELS_PATH=./testdata
          python3 ./modules/mo_pytorch/test.py
